name: wizard-coder

dependencies:
  - python=3.10
  - numpy
  - pip:
    - rouge_score
    - fire
    - openai
    - sentencepiece
    - wandb
    - torch==2.0.1
    - transformers==4.29.2
    - datasets
    - deepspeed==0.9.2 
    - accelerate
    - tensorboardX
